CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_POINTING=y

# Native Zephyr PMW3610 driver (Zephyr 4.1+)
CONFIG_INPUT_PMW3610=y

CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Central-only configs (right side is central)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

CONFIG_BT_CTLR_PHY_2M=y
# Make the OLED dimmer – 0 = completely off, 255 = full brightness, 128 = default
CONFIG_SSD1306_DEFAULT_CONTRAST=40